In [2]:
import pandas as pd
import raphtory as rp

In [3]:
mega_df = pd.read_json("mega_scrape_1.json")  
mega_df.head()

,id,id_str,name,screen_name,location,description,url,entities,protected,followers_count,...,advertiser_account_type,advertiser_account_service_levels,analytics_type,business_profile_state,translator_type,withheld_in_countries,require_some_consent,type,target_username,email
0,954832889350443000,954832889350443008,Moxy Rolla 🇨🇦🇵🇸🔻,WoodstockSusie,"Woodstock, Ontario",Proud Progressive Canadian🇨🇦\nRebel Artist\n'H...,NaN,{'description': {'urls': []}},False,2603,...,none,[],disabled,none,none,[],False,follower,DenyThemEssence,NaN
1,2516920201,2516920201,Dave Ravicher,Whtapl,Global,Zionism will be defeated and there will be a h...,NaN,{'description': {'urls': []}},False,4859,...,none,[],enabled,none,none,[],False,follower,DenyThemEssence,NaN
2,3357427702,3357427702,MommaMarDee radical; healthcare as a Right⚖️🖤,b1e56df9ce6549f,usa,"human being, person, individual, coen bros. ch...",NaN,{'description': {'urls': []}},False,7138,...,none,[],enabled,none,none,[],False,follower,DenyThemEssence,NaN
3,1846992056096579600,1846992056096579584,Dr. Nuran Akgören,nurunnisaRa,Earth,"https://t.co/A49mX4NaxJ.Neurology, Neuroscienc...",NaN,{'description': {'urls': [{'url': 'https://t.c...,False,3477,...,none,[],disabled,none,none,[],False,follower,DenyThemEssence,NaN
4,225838288,225838288,George R. Mutt 🌎,Georgiemutt,Texas,I used to be a fun loving mutt working towards...,NaN,{'description': {'urls': []}},False,4673,...,none,[],enabled,none,none,[],False,follower,DenyThemEssence,NaN

In [4]:
mega_df_2 = pd.read_json("mega_scrape_2.json")

In [5]:
mega_df_3 = pd.read_json("mega_scrape_3.json")

In [6]:
mega_df_e = pd.read_json("mega_scrape_e.json")

In [7]:
mega_df_final = pd.concat([mega_df, mega_df_2, mega_df_3, mega_df_e], ignore_index=True)
mega_df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 302612 entries, 0 to 302611
Data columns (total 66 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   id                                  302612 non-null  int64
 1   id_str                              302612 non-null  int64
 2   name                                302612 non-null  str
 3   screen_name                         302612 non-null  str
 4   location                            302612 non-null  str
 5   description                         302612 non-null  str
 6   url                                 66890 non-null   str
 7   entities                            302612 non-null  object
 8   protected                           302612 non-null  bool
 9   followers_count                     302612 non-null  int64
 10  fast_followers_count                302612 non-null  int64
 11  normal_followers_count              302612 non-null  int64
 12  friends_count                       302612 non-null  int64
 13  listed_count                        302612 non-null  int64
 14  created_at                          302612 non-null  datetime64[us, UTC]
 15  favourites_count                    302612 non-null  int64
 16  utc_offset                          0 non-null       float64
 17  time_zone                           0 non-null       float64
 18  geo_enabled                         302612 non-null  bool
 19  verified                            302612 non-null  bool
 20  statuses_count                      302612 non-null  int64
 21  media_count                         302612 non-null  int64
 22  lang                                0 non-null       float64
 23  status                              253457 non-null  object
 24  contributors_enabled                302612 non-null  bool
 25  is_translator                       302612 non-null  bool
 26  is_translation_enabled              302612 non-null  bool
 27  profile_background_color            302612 non-null  str
 28  profile_background_image_url        116447 non-null  str
 29  profile_background_image_url_https  116447 non-null  str
 30  profile_background_tile             302612 non-null  bool
 31  profile_image_url                   302612 non-null  str
 32  profile_image_url_https             302612 non-null  str
 33  profile_banner_url                  205938 non-null  str
 34  profile_link_color                  302612 non-null  str
 35  profile_sidebar_border_color        302612 non-null  str
 36  profile_sidebar_fill_color          302612 non-null  str
 37  profile_text_color                  302612 non-null  str
 38  profile_use_background_image        302612 non-null  bool
 39  has_extended_profile                302612 non-null  bool
 40  default_profile                     302612 non-null  bool
 41  default_profile_image               302612 non-null  bool
 42  pinned_tweet_ids                    302612 non-null  object
 43  pinned_tweet_ids_str                302612 non-null  object
 44  has_custom_timelines                302612 non-null  bool
 45  can_media_tag                       302612 non-null  bool
 46  followed_by                         302612 non-null  bool
 47  following                           302612 non-null  bool
 48  live_following                      302612 non-null  bool
 49  follow_request_sent                 302612 non-null  bool
 50  notifications                       302612 non-null  bool
 51  muting                              302612 non-null  bool
 52  blocking                            302612 non-null  bool
 53  blocked_by                          302612 non-null  bool
 54  advertiser_account_type             302612 non-null  str
 55  advertiser_account_service_levels   302612 non-null  object
 56  analytics_type                      302612 non-null  str
 57  business_profile_state              302612 non-null  str
 58  translator_type                     302612 non-null  str
 59  withheld_in_countries               302612 non-null  object
 60  require_some_consent                302612 non-null  bool
 61  type                                302612 non-null  str
 62  target_username                     302612 non-null  str
 63  email                               3526 non-null    str
 64  withheld_scope                      5 non-null       str
 65  is_lifeline_institution             28 non-null      float64
dtypes: bool(22), datetime64[us, UTC](1), float64(4), int64(10), object(6), str(23)
memory usage: 225.9+ MB

In [8]:
mega_df_final.columns

Index(['id', 'id_str', 'name', 'screen_name', 'location', 'description', 'url',
       'entities', 'protected', 'followers_count', 'fast_followers_count',
       'normal_followers_count', 'friends_count', 'listed_count', 'created_at',
       'favourites_count', 'utc_offset', 'time_zone', 'geo_enabled',
       'verified', 'statuses_count', 'media_count', 'lang', 'status',
       'contributors_enabled', 'is_translator', 'is_translation_enabled',
       'profile_background_color', 'profile_background_image_url',
       'profile_background_image_url_https', 'profile_background_tile',
       'profile_image_url', 'profile_image_url_https', 'profile_banner_url',
       'profile_link_color', 'profile_sidebar_border_color',
       'profile_sidebar_fill_color', 'profile_text_color',
       'profile_use_background_image', 'has_extended_profile',
       'default_profile', 'default_profile_image', 'pinned_tweet_ids',
       'pinned_tweet_ids_str', 'has_custom_timelines', 'can_media_tag',
       'followed_by', 'following', 'live_following', 'follow_request_sent',
       'notifications', 'muting', 'blocking', 'blocked_by',
       'advertiser_account_type', 'advertiser_account_service_levels',
       'analytics_type', 'business_profile_state', 'translator_type',
       'withheld_in_countries', 'require_some_consent', 'type',
       'target_username', 'email', 'withheld_scope',
       'is_lifeline_institution'],
      dtype='str')

In [9]:
mega_df_simple = mega_df_final[["name","screen_name", "location", "url", 'followers_count', 'friends_count', 'created_at', 'utc_offset', 'statuses_count', 'verified', 'target_username']]
mega_df_simple.sample(10)

,name,screen_name,location,url,followers_count,friends_count,created_at,utc_offset,statuses_count,verified,target_username
262372,Amo jimmy Mo,yaba502,United States of Zift,NaN,1852,1574,2011-02-02 21:32:15+00:00,NaN,14780,False,RIPGeorgeHabash
40389,GÜNEŞ,GNE261936689134,,NaN,1656,2799,2026-01-22 18:26:05+00:00,NaN,10852,False,SangZhi260
71203,Camille🚜 Evert 🇨🇵,camilleve2000,Mulhouse France,NaN,2962,3734,2012-05-02 09:22:49+00:00,NaN,20267,False,tchemtcem
202220,Akmall48,akmall48,"Tangerang, Banten",NaN,199,1305,2021-08-16 23:53:55+00:00,NaN,261,False,qaizimi
83587,Mouâd ムアーッド🐈 📻,medmouad,Agadir,https://t.co/sCGsfnilf0,4627,4899,2008-11-06 13:27:25+00:00,NaN,444065,False,mayasdreams
20507,Ayomprop,the_ayomprop,creating iconic rhythms 🛼🪗,NaN,1181,1345,2020-10-06 16:29:36+00:00,NaN,377,False,Iamdotun4
156977,rami saleim,GSFILMS1,,NaN,706,7463,2020-01-05 00:43:58+00:00,NaN,221,False,fightBackAnon
273439,Laura Arroyo,menoscanas,Peruana sin fecha de retorno,https://t.co/OPYkqKsNZA,89800,4138,2009-08-20 21:19:31+00:00,NaN,103752,False,YoCambio20D
36930,Sobia ch,walay76055,,NaN,446,1246,2024-05-09 17:39:37+00:00,NaN,22983,False,Revolution93843
8779,Rose Bermingham-Shaw,RoseB_Shaw,,NaN,56,163,2010-11-15 21:55:34+00:00,NaN,2600,False,TheBirmingham6

In [10]:
mega_df_simple.sample(10)

,name,screen_name,location,url,followers_count,friends_count,created_at,utc_offset,statuses_count,verified,target_username
78332,ईशु _ओसियाँ,nebour25,भारत,https://t.co/RtOkcWN0CX,3973,7269,2019-10-19 14:03:03+00:00,NaN,2412,False,Mr_Bhagat08
148571,DeFiGuru,DeFiGuru67,,NaN,564,3378,2025-02-20 14:03:26+00:00,NaN,5,False,JoannaTeglund
254507,Torraine Walker,TorraineWalker,,https://t.co/jTJNP09XzW,82273,920,2014-09-16 22:40:42+00:00,NaN,71053,False,zapanterablack
112129,Ahmad,abuahma56986820,,NaN,899,6914,2020-05-09 23:18:55+00:00,NaN,6927,False,DKLarge2
59475,A.B.O.L.L.F.A.Z.L,ABOLLFA49861832,,NaN,164,3329,2023-03-11 04:43:11+00:00,NaN,10,False,Soureh_design2
99392,José marti,elfegofila,,NaN,116,286,2022-08-30 16:24:46+00:00,NaN,360,False,ElsyObradorova
14672,Linda Tallons #Peace&Justice,LindaTallons,Selby North Yorkshire,NaN,3690,4303,2012-09-16 06:29:19+00:00,NaN,97324,False,TheBirmingham6
61372,Laith Jaar,laithjaar99,Palestine,NaN,1438,6999,2012-11-27 13:52:12+00:00,NaN,517,False,Soureh_design2
183024,kakasloi,supramabuhay,World,NaN,158610,1120,2017-09-27 15:32:45+00:00,NaN,899,False,xixiltik
142718,Rocío,Roco93201462,,NaN,3623,3967,2020-04-28 17:20:27+00:00,NaN,200777,False,YoCambio20D

In [11]:
mega_df_simple.to_csv("mega_df_simple.csv", index=False)

In [12]:
import itertools 
from collections import defaultdict

In [13]:
cols = mega_df_simple.columns.tolist()
cols.insert(0, cols.pop(cols.index("target_username")))
mega_df_simple = mega_df_simple[cols]
mega_df_simple.head()

,target_username,name,screen_name,location,url,followers_count,friends_count,created_at,utc_offset,statuses_count,verified
0,DenyThemEssence,Moxy Rolla 🇨🇦🇵🇸🔻,WoodstockSusie,"Woodstock, Ontario",NaN,2603,5970,2018-01-20 21:47:55+00:00,NaN,71701,False
1,DenyThemEssence,Dave Ravicher,Whtapl,Global,NaN,4859,5044,2014-05-23 03:10:00+00:00,NaN,287467,False
2,DenyThemEssence,MommaMarDee radical; healthcare as a Right⚖️🖤,b1e56df9ce6549f,usa,NaN,7138,6746,2015-07-03 20:03:56+00:00,NaN,1235324,False
3,DenyThemEssence,Dr. Nuran Akgören,nurunnisaRa,Earth,NaN,3477,2352,2024-10-17 19:10:28+00:00,NaN,27581,False
4,DenyThemEssence,George R. Mutt 🌎,Georgiemutt,Texas,NaN,4673,4062,2010-12-12 15:45:55+00:00,NaN,350966,False

In [14]:
target_followers = defaultdict(set)

for _, row in mega_df_simple.iterrows():
    target_followers[row['target_username']].add(row['screen_name'])

target_followers

defaultdict(set,
            {'DenyThemEssence': {'H_H_Elfrink',
              'Enolla49',
              'noelzebub',
              'SteveTheHealer',
              'OlgaBazova',
              'selqet',
              'rixdig',
              'Bunina17',
              'homesickalien80',
              'altrestell',
              'RothmanProphecy',
              'jpaniagua',
              's43381113',
              'Howard_Nutlick',
              'AlwaysForward88',
              'Xixxax2',
              'gatica_deborah',
              'MuhammedLa99679',
              'TheDarkFacts',
              'NabeelaAkh',
              '_The_Wub_',
              'SlotteBren70687',
              'nowwerevolt',
              'bradyrainey',
              'DeepMKUltra',
              'Birdman196007',
              'GirAlam1',
              'PamelaTheZ',
              'AngletonOrchids',
              'NikolaiNvolkov',
              'Don_Angelo_',
              'DelaneyTempest',
              'adri16',
              'WendyFriedman66',
              'brinkman_b',
              'L3mino',
              'RomanoBenedetti',
              'WaldenE',
              'beanie_jones',
              'Cherri74887119',
              'fishman2131',
              'AlexSad75177637',
              'jai_lies',
              'prisonerroom101',
              'roskioski',
              'Zorn_Gottes_1',
              'GianniZmano',
              'Bamford43',
              'Zer0Non92396',
              'Paddystinian',
              'flockouttahere',
              'JustKarkarov',
              'bruce_krug',
              'berningman16',
              'JE_Maleta',
              'Valeria_Cas22',
              'CDZ_999',
              'AdrianAntonioli',
              'samhusseini',
              'GhostAnneBoleyn',
              'Jinx_Kele',
              'Jegdda',
              'qyacke',
              'CmookieB',
              'Gumedemamlambo',
              'KarlGolovin',
              'DemocraticIs',
              'C0smicVagab0nd',
              'jvgraz',
              'Jonescrusher11',
              'Tinfoil_Travis',
              'ShooterLibby',
              '8zal',
              'Dienne_7',
              'UbuntuForever',
              'mike_jefford96',
              'walnuttunlaw',
              'ArisP61979004',
              'haleew2020',
              'inovajon',
              'Smoki2021',
              'kittensmittenz',
              'gueatcn',
              'Marlonkesler11',
              'JeanMarat7',
              'HorsesVSCenk',
              'ClimateCompadre',
              'JohnTitor137',
              'GameshBill',
              'notails',
              'MarcKalmijn',
              'HawkEye02723358',
              'miamivicemami',
              'Aksol_77',
              'mabian',
              'shaikhdanyal08',
              'mjCarefree',
              'thisgirlafrayed',
              'ArcaVorago',
              'tris92486',
              'RoqieRaccoon',
              'Cheese12987',
              '_rickyrants_',
              'Anshkaushikk',
              'markvdijken',
              'adjectivenoun',
              'gabriel_ramini',
              'ForceTheVoteM4A',
              'Alamada10',
              'DSelfishMan',
              'marlazingerrr',
              'KwameAs40431858',
              'jeddy1214',
              'BoltzmannBooty',
              'MrKipwood',
              'KimDorrob',
              'J_Patrick_Scott',
              'LondoMollari13',
              'theSmokingGun27',
              'AgentScorpion1',
              'hamedasgarpanah',
              'GracchusT1',
              'Hallucibacon',
              'reitano_arthur',
              'NarcJoeKennedy',
              'Long_Archer',
              'KlonnyPin_Gosch',
              'EssSamaneh',
              'McSophrosyne',
              'CatVSHumanity',
              'VoxRogamus',
              'freckle_red',
              'AlsulTan2060',
              'UdsiAsli',
              'mrquake1996',
              'CaitNoMoreWars',
              'Jason88nosaJ',
              'FaithfulGarden',
              'zoyaislove',
              'BureakNelly',
              'ChenangoBango76',
              'FarhanK24953',
              'A6Freedom',
              'gphds1',
              'zhukovzhuk03',
              'e_galv',
              'RizDaBiz1',
              'bzew',
              'lovebizarre1',
              'mgcroteau',
              'ChrisRulon',
              'KingTherapy',
              'DenaKhalafallah',
              'RothLindberg',
              'ResidentsCorner',
              'marindatanow',
              'afghanbot',
              'turikat',
              'janetsnakehole0',
              'conzmoleman',
              'nim_zm',
              'fxcstatic',
              'DonnyDeYoung1',
              'BernieRoronoa',
              'Schnubberschnup',
              'blindobserver0',
              'Greg_Ayiman',
              'SohoVFX',
              'TruthTo1777148',
              'TManFilmGuy',
              'nuephilosophi',
              'Sharkdoge11',
              'LumpyLouish',
              'wherepond',
              'whale_collector',
              'JanezoviNasveti',
              'AB32877',
              'HellaIndieGuy',
              'TristenSchmidt',
              'ProudSocialist',
              'WoodyTIND23',
              'jessemarioneau',
              'benigma2017',
              'CorporatistN',
              'BayosHarmonicas',
              'Philip_A_Gibson',
              'jacubkobak',
              'YoungShastri',
              'redistribu11188',
              'jakki_jax',
              'alongtimegoner',
              'RitchiePrice3',
              'undrcvrbrothr',
              'Poppywillow14',
              'KittenXenia',
              'fixurheart2016',
              'Irisschanyu',
              'AnythingExceptT',
              'incognitohibou',
              'CouplesWater',
              'glenn_davisson',
              'TwayenA',
              'RealRoomanus',
              'ROsariban44817',
              'Thomas_Dahl',
              'BernieEffect',
              'PamphletsY',
              'truxyz',
              'anony_work',
              'FvrDrms',
              'Winslow20Don',
              'esqgirl2',
              'indicordis',
              'Lucia4115511831',
              'paleocybernetic',
              'Guattari1',
              'w_nicht',
              'MattVarns1',
              'NoManland667',
              'Ollies__Army',
              'CatJova',
              'foe_of_the_show',
              'leftfielder',
              'prd_perspective',
              'ghost_youth',
              'KathleenJorge20',
              'LFCneartheD',
              'redemptionsteps',
              'JeremyWard33',
              'PeterSchlusche',
              'BustaJoke',
              'urLogicIsAfam',
              'BAboueleinein',
              'MCCLALifeDraw',
              'Lukyluke311',
              'caosgeral',
              'yugoslav_luka',
              'iamjourjean',
              'BlackBeans4eva',
              'constage123',
              'kavn',
              'northwoods_memo',
              'DJDesign90',
              'DookieSweat',
              'AceMarxist',
              'Petepel1776',
              'retorikku',
              'katt_zia',
              'RRalphBartley',
              'ajtsok',
              'DavidSommers5',
              'prehistori66528',
              'jaredi_r',
              'EdVenture9',
              'TaylorMcFayden',
              'bcauler',
              'aiming4themoon',
              'hbsandpiper',
              'HighwaySqueak',
              'eric_kleppel',
              'AlexS00079104',
              'Gongon45193627',
              'ArmchairSt88474',
              'FaerieWhings',
              'MyNameIsRed11_',
              'redboatandrew',
              'Tonton93386936',
              'ctroughton7',
              'AlchemicalDaddy',
              'bigtoughboice',
              'SeanJohnGacy_',
              'nb_mao',
              'Hasadwan',
              'faliqfahmie',
              'Nin39Nine',
              'EchoingStardust',
              '0CarbonCopy0',
              'c29078208',
              'FlashpointsNews',
              'Beautynature_',
              'Jsblu549',
              'cpudog',
              'Library_Raccoon',
              'BadAssShrink',
              'GladioRossa',
              'edward_bernayz',
              'The96Revolution',
              'scopeman09',
              'Avshalom1000bc',
              'ince_dudu29910',
              'ccnameisfriday',
              'GeorgeBTonks',
              'aint_no_thaang',
              'NestPasUnPsyop',
              'CarlosI90141560',
              'ripcitythug',
              'J0000000000000_',
              'fourthreichpod',
              'tjmussett',
              'zacharonipizza',
              'UnionBustingBot',
              'mohanadmazen04',
              'JamesVRL',
              'JJDemonic',
              'andrewmeindl',
              'Manishmenna',
              'JessicaS3647',
              'PoliticalMemes5',
              'jonstall2016',
              'TheReal1908',
              'misamdoi',
              'shannonsharleen',
              'bonzerbarry',
              'Stukuls',
              'ynkybstrd123',
              'MatMegan',
              'palestiniankid',
              'EnuscaVeronica',
              'szc1220',
              'Athlete1m',
              'DoctorFishbones',
              'mntnwzrd66',
              'apoplexual',
              'XC_xiuren',
              'versollato',
              'RogueKite',
              'Caboose_GA',
              'VoxofGod',
              'c_saw0000',
              'JPsGhost',
              'TsitsiaMaria',
              'shakur424',
              'Sinizt3r1',
              'eigenkirkbot',
              'JACk88431259',
              'Xi4Atlanta',
              'birthplacearth',
              'jeffb724',
              'Jerry44939',
              'leilacleigh',
              'Tree_Top_Dr',
              'MusicMiscreant',
              'morte2631a',
              'FuckAIPAC',
              'ConsortRed',
              'sinklord',
              'Alhamask',
              'JoshuaBessom',
              'zakkupo',
              'Olicka17_Q',
              'CowardlyCommie',
              'wiesiede',
              'Vergniaud99',
              'Words_Of_Will_',
              'ThomasC40902822',
              'Magus_Simon8100',
              'jfredfern',
              'bereZoVsk1y',
              'FkNATO_FkWEF',
              'marioskyjuice',
              'danclingan',
              'Amiebrooke_',
              'deepdishnation',
              'weeblovestoons',
              'donnyonyea',
              'stscholasticas',
              'Julie76983198',
              'peacemonger420',
              'DemonAesthete',
              'BrownAreolaLola',
              'DysNewsBreak',
              'DD_Geopolitics',
              'shmeckle666',
              'LauraWasABerner',
              'DGosdantian',
              '0x_trajekty',
              'piskendeger',
              'LancsMaverick',
              'Ikejiobodo',
              'ZishanHasan0',
              'drbairdonline',
              'LongerTables',
              'millsianism',
              'Michele_Quasimo',
              'always_angry88',
              'IvanBuchanJanus',
              'GosiaKrawczyk00',
              'Bevin83994661',
              'Sonya999888',
              'WeAreNotAsking',
              'bazzbae1919',
              'Franka1357',
              'Michel21968',
              'ImzMK1',
              'YouAvaGoodPoint',
              'ketchmeifucan',
              'frecklesfracker',
              'Zeno25',
              'Elena5911722614',
              'ccnameissunday',
              'Redcommiejonny',
              'andresha_bass',
              'sabrina68',
              'JillStallard3',
              'Kamokurulusu',
              'DenimFarmer',
              'macmaster_d',
              'AliciaandAlicia',
              'DgenXer',
              'ptrhearne',
              'yyyanon888',
              'PhonkArt',
              'phortuenti',
              'leftylucieb',
              'AZeglicki',
              'ivor_2012',
              'ghostdog310',
              'AyaAlGhazzawi',
              'A_I_Vantra',
              'Lacey817766',
              'Rahmanzaynay',
              'IreneBertoni66',
              'freethought987',
              'wild_situation',
              'Patriot_Eke',
              'DoodooWorld',
              'Marc__ZOV_',
              'jackisaacwise',
              'haamemezayn',
              'NGTGBetter',
              'karloui',
              'care_bear444',
              'jaccocharite',
              'DDadabi',
              'JewRussophile',
              'Young_Khomeini',
              'DavidBo03050197',
              'counterfitt',
              'grilakos',
              'DavidRotous',
              'zxcdsd234',
              'dgjewel',
              'DecransArno',
              'libertadorzn',
              'Celinaqattan',
              'd__e_p',
              'Cooey10',
              '5253United',
              'tu95overlangley',
              'doomento',
              'ExtraBulla',
              'mattakersmusic',
              'godzuki2fu',
              'NonViolentNigga',
              '_visual',
              'LKwarcinski',
              '21WIRE',
              'DoctorNova85',
              'WadeTurnbull',
              'Upstate_Life',
              'toastedavocado2',
              'Reine__Audu',
              'lizardbreakfast',
              'doctor_cabral',
              'MichaelSandstro',
              'mail2bruce',
              'jackiemae3188',
              'glp4n0g7',
              'humanitari62701',
              'misterchambo',
              'BubblesToBurst',
              'fxlxfel',
              'FrankZollo',
              'propeace_bot',
              'jenben1969',
              'AjazNoor',
              'Piter920611',
              'CasulaSurendar',
              'oHDGx',
              'OctoY1',
              'pozharniysham17',
              'Diomedes2023',
              'b1e56df9ce6549f',
              'AboundingMyths',
              'JohnSmith3850',
              'mrs_socialista',
              'sisterMuxi',
              'DrLeoMarvin5',
              'JenD1974',
              'PeterMayonnaise',
              '917Brett',
              'LDelsoll',
              'marlbororibs',
              'lazaman77',
              'LibrulsAzzole',
              'WilhelmMyhre',
              'Greyhou20147206',
              'SiaFreeGaza',
              'jordsjailacc',
              'socialistpisces',
              'SteffiNYC70',
              'A2da4s',
              'KebabKunt',
              'irish_racer',
              'ravelesm',
              'commie_zombie',
              'dirtbag_atx',
              'TkKoza',
              'toddjersey',
              'thenelipas',
              'iSchlakman',
              'isboththesame',
              'RoninAmongChaos',
              'propidiumiodide',
              'HInsurgente',
              'SpittinVenoms',
              '11neffable',
              'SandersAlabama',
              'normal42069',
              'zhonnymao',
              'berniebernie546',
              'gniadball',
              't_sfea',
              'zhouenlai2024',
              'dead_vape_maree',
              'KayyOnFire',
              'Kinkajou5123',
              'WagnerAmb1W9',
              'backcuntrybish',
              'deedwithcorpses',
              'stellarium33',
              'SocialistRage',
              'MichW1138',
              'RepublicWelsh',
              'Yawn_Lennon',
              'BernForBernie20',
              'PullWeeds',
              'futurprogressiv',
              'pax_orbis',
              'laughingcat2016',
              'ubiqunity',
              'WilliamRamseyIn',
              'Siilisuni',
              'VladimirOulian6',
              'kaliwave',
              'Nerbil',
              'SlayerTerminal',
              'TheSpecter9',
              'rogue_wallaby',
              'jccsomody',
              'chris_darnielle',
              'HEncore49002',
              'LostMillions',
              'Charlie24999736',
              'sigridfelic1',
              'lobotomizeland1',
              'categuerrical',
              'babywhitemonkey',
              'ComradeHazet36',
              'dino_pegoraro',
              'nozerohere',
              'alanlan66618745',
              'didntknow507',
              'EGA_Prince',
              'QueenWraps',
              'CremerVsCremer',
              'TheUprising2025',
              'TijsHardam',
              'dokurzaaku',
              'AndyTraenkner',
              'romiyoyo2018',
              'peterdaledeath',
              '10pencefreddo',
              'fred_schmutz',
              'Col_Olly_North',
              'Luckynu777',
              'JJ65910824',
              'RedHector216',
              'jorgeolo',
              'niall_east',
              'SaraWGreen',
              '4thegoodofwhom',
              'Shaza2711',
              'jichmack',
              'LordRasputin',
              'its_unravelling',
              'Playdoh59048217',
              'RUSSELL08950362',
              'wmichaelsw',
              'AkademiskC',
              'newslexi',
              'CarmenStuder',
              'NuScooters',
              'mazzenilsson',
              'onewiseburdman',
              'kin0therapy',
              'Suzanmonkey',
              'goddessartist',
              'rupturedhaze',
              'YiSiping',
              'Dissolvingdoor',
              'Ed39739215',
              'SummerAlpha',
              'NABEELRAJAB',
              'iwl2ke95',
              'sharon_beartrac',
              'Onmywaykelllee',
              'JohnWal43673294',
              'percsmoker',
              'Crazyfoxx13',
              'ancient__catbus',
              'cimexo',
              'debbiedoo131',
              'repressedmems',
              'carwashmlkshkes',
              'girl_fieri__',
              'bisan217',
              'HinckleyJrJr',
              'DoomScrollingML',
              'teatotalitarian',
              'JamesQether',
              'good4gaia',
              'RMarsh64387',
              'RoseChung1987',
              '83RepentAndObey',
              'IdealistCynic',
              'Sweetbarbaralee',
              '_trichomes_',
              'dan_won',
              '1WhiteRabbitt',
              'American_Gladio',
              'sortitioncrank',
              'scolaire91',
              'hetvaltnietmee',
              'A_RoomWithAView',
              'EdScherrer',
              'GSFedayeen',
              'BlueCheckBeth',
              'utquamvolvo',
              'OWS_ellie',
              'AdamG52676399',
              'js44095',
              'not_mariya',
              'MonaLisas45',
              'Kiratsuki01',
              'elleloves_09',
              'ChrisFrancis54',
              'LKumar65529511',
              'jackxyz7',
              'illuminarts1972',
              'Bad_Writer0111',
              'mrgubkin',
              'fsanleec',
              'jasinskm',
              'Reemsky1988',
              'naked_copy',
              'kate___said',
              'beersnbikes',
              '5candyman',
              'i_and_ar',
              'PaulSansonetti',
              'wiisekey',
              'BUDDYHEAD_',
              'mildred_florsh',
              'MohAlgebaly',
              'AmericanDevine1',
              'Brunchingwithk1',
              'realCEOofANTIFA',
              'yakuzapunk',
              'dononerobantonw',
              'elahieh',
              'af3zzz',
              'skye_daddy',
              'IOW666',
              'OGsamboslice',
              'makebasmoon',
              'hex_init',

In [15]:
results = []
for t1, t2 in itertools.combinations(target_followers, 2):
   shared = len(target_followers[t1].intersection(target_followers[t2]))
   if shared >= 3:
     results.append((t1, t2, shared))

results.sort(key=lambda x: x[2], reverse=True)
results[:10]

[('JeSuis34C', 'ElsyObradorova', 2237),
 ('Soureh_design2', 'ExplosiveMediaa', 1448),
 ('fahimiqbalemon', 'Richard_Prins', 983),
 ('Richard_Prins', 'RIPGeorgeHabash', 917),
 ('Richard_Prins', 'DKLarge2', 754),
 ('Mima091203', 'Richard_Prins', 662),
 ('mayasdreams', 'Richard_Prins', 644),
 ('fahimiqbalemon', 'DKLarge2', 640),
 ('fahimiqbalemon', 'RIPGeorgeHabash', 638),
 ('Richard_Prins', 'ezbiderman', 630)]

In [16]:
len(results)
df_results = pd.DataFrame(results, columns=["target1", "target2", "shared_followers"])
df_results

             target1          target2  shared_followers
0          JeSuis34C   ElsyObradorova              2237
1     Soureh_design2  ExplosiveMediaa              1448
2     fahimiqbalemon    Richard_Prins               983
3      Richard_Prins  RIPGeorgeHabash               917
4      Richard_Prins         DKLarge2               754
...              ...              ...               ...
1607     YoCambio20D    fightBackAnon                 3
1608   JoannaTeglund      Ashborn_110                 3
1609          GM7077      Ashborn_110                 3
1610   fightBackAnon      Ashborn_110                 3
1611     Ashborn_110     Abra_Company                 3

[1612 rows x 3 columns]

In [34]:
df_results.to_csv("shared_followers.csv", index=False)

In [17]:
df_final = df_results.merge(mega_df_simple[["target_username", "followers_count","created_at"]].drop_duplicates(), left_on="target1", right_on="target_username").rename(columns={"followers_count": "target1_followers"}).drop(columns=["target_username"])

df_final = df_final.drop_duplicates(subset=["target1", "target2"])

df_final

,target1,target2,shared_followers,target1_followers,created_at
0,JeSuis34C,ElsyObradorova,2237,1657,2020-04-12 14:07:53+00:00
6004,Soureh_design2,ExplosiveMediaa,1448,1192,2011-09-14 16:07:33+00:00
26004,fahimiqbalemon,Richard_Prins,983,279,2010-02-09 09:41:21+00:00
28893,Richard_Prins,RIPGeorgeHabash,917,2,2025-07-24 13:26:40+00:00
36309,Richard_Prins,DKLarge2,754,2,2025-07-24 13:26:40+00:00
...,...,...,...,...,...
5518178,YoCambio20D,fightBackAnon,3,1899,2011-12-12 23:33:05+00:00
5528534,JoannaTeglund,Ashborn_110,3,1247,2025-09-29 20:10:41+00:00
5538014,GM7077,Ashborn_110,3,301,2025-07-07 01:45:42+00:00
5539344,fightBackAnon,Ashborn_110,3,19,2025-11-29 09:17:10+00:00
5541529,Ashborn_110,Abra_Company,3,783,2025-08-23 03:33:05+00:00

In [18]:
g = rp.Graph()

g.load_nodes(
  data=df_final,
  id="target1",
  time="created_at",
)

g.load_edges(
  data=df_final,
  src="target2",
  dst="target1",
  time="created_at",
)
print(g)

HBox(children=(HTML(value=''), IntProgress(value=0, max=1612), HTML(value='')))

HBox(children=(HTML(value=''), IntProgress(value=0, max=1612), HTML(value='')))

Graph(number_of_nodes=78, number_of_edges=1612, number_of_temporal_edges=1612, earliest_time=EventTime(timestamp=1236156014000, event_id=0), latest_time=EventTime(timestamp=1775582468000, event_id=18446744073709551615))

In [21]:
import os
working_dir = "graphs_3/"

if not os.path.exists(working_dir):
    os.makedirs(working_dir)
g.save_to_file(working_dir + "new_graph")

In [22]:
from raphtory import Graph
from raphtory.graphql import GraphServer, RaphtoryClient
import tempfile

In [23]:
tmp_work_dir = tempfile.mkdtemp()
server = GraphServer(tmp_work_dir).start()

  2026-04-10T13:28:26.622289Z  INFO raphtory_graphql::server: UI listening on 0.0.0.0:1736, live at: http://localhost:1736
    at raphtory-graphql/src/server.rs:217

In [24]:
client = server.get_client()
client.send_graph(path="g", graph=g)

query = """{graph(path: "g") {nodes {list {name}}}}"""
result = client.query(query)
print("Query via server.get_client():")
print(result)

Query via server.get_client():
{'graph': {'nodes': {'list': [{'name': 'silversinergy'}, {'name': 'qaizimi'}, {'name': 'JeSuis34C'}, {'name': 'UthamakiKE'}, {'name': 'BenUzi19770'}, {'name': 'Soureh_design2'}, {'name': 'ouitrvl'}, {'name': 'Richard_Prins'}, {'name': 'DKLarge2'}, {'name': 'ezbiderman'}, {'name': 'TheBirmingham6'}, {'name': 'RIPGeorgeHabash'}, {'name': 'KeivanS5'}, {'name': 'fahimiqbalemon'}, {'name': 'Mima091203'}, {'name': 'mayasdreams'}, {'name': 'farahadams'}, {'name': 'ysinvacaciones'}, {'name': 'RGemmell75'}, {'name': 'Oldbag12345'}, {'name': 'bobreone'}, {'name': 'EBRU24071923'}, {'name': 'fonzooe'}, {'name': 'ieaglewatch'}, {'name': 'DenyThemEssence'}, {'name': 'zapanterablack'}, {'name': 'zaibx'}, {'name': 'vulgarboatman'}, {'name': 'qqggpp86'}, {'name': 'anniefofani'}, {'name': 'JoannaTeglund'}, {'name': 'Anonymouso32196'}, {'name': 'xixiltik'}, {'name': 'elinggalatif'}, {'name': 'tchemtcem'}, {'name': 'Just_Ayiex'}, {'name': 'MontahaTarabey'}, {'name': 'YoCambio20D'}, {'name': 'moore_lynz45577'}, {'name': 'FernandezManu81'}, {'name': 'WOTCHA999'}, {'name': 'RHJOfficial'}, {'name': 'ModigWoman'}, {'name': 'xenosstinkriti2'}, {'name': 'Soundararajansm'}, {'name': 'Person453112'}, {'name': 'Revolution93843'}, {'name': 'txemasg'}, {'name': 'untung_armi'}, {'name': 'Bas642654743206'}, {'name': 'alihstem'}, {'name': 'NocturnalDoom'}, {'name': 'Mr_Bhagat08'}, {'name': 'GhaithAhmed117'}, {'name': 'preetijjain'}, {'name': 'Hessamedia'}, {'name': 'ElsyObradorova'}, {'name': 'TimChowd'}, {'name': 'SangZhi260'}, {'name': 'Ashborn_110'}, {'name': 'jethalaalhu'}, {'name': 'bibishalom330'}, {'name': 'd_normyle0'}, {'name': 'MudassarAKLodhi'}, {'name': 'bornwanderer2'}, {'name': 'GM7077'}, {'name': 'fightBackAnon'}, {'name': '209asif'}, {'name': 'relewinde'}, {'name': 'EnriqueGarcaSo8'}, {'name': 'BeingHasan0'}, {'name': 'mannaggiaDegll'}, {'name': 'risoflo'}, {'name': 'Abra_Company'}, {'name': 'ExplosiveMediaa'}, {'name': 'Gokturk0034'}, {'name': 'malik_musa14350'}, {'name': 'Iamdotun4'}]}}}

In [25]:
from raphtory import algorithms

pagerank = algorithms.pagerank(g)

df_rank = pd.DataFrame({
    "account": pagerank.nodes(),
    "score": [v["pagerank_score"] for v in pagerank.values()]
}).sort_values("score", ascending=False)

print(df_rank.to_string(index=False))

                                                                                                                                                   account    score
  Node(name=DenyThemEssence, earliest_time=EventTime(timestamp=1516484875000, event_id=85), latest_time=EventTime(timestamp=1516484875000, event_id=3096)) 0.138011
      Node(name=WOTCHA999, earliest_time=EventTime(timestamp=1516484875000, event_id=2767), latest_time=EventTime(timestamp=1773556779000, event_id=3102)) 0.110885
   Node(name=TheBirmingham6, earliest_time=EventTime(timestamp=1313798783000, event_id=15), latest_time=EventTime(timestamp=1773556779000, event_id=1783)) 0.070669
      Node(name=RGemmell75, earliest_time=EventTime(timestamp=1772827192000, event_id=147), latest_time=EventTime(timestamp=1773556779000, event_id=1998)) 0.062047
     Node(name=farahadams, earliest_time=EventTime(timestamp=1313798783000, event_id=1735), latest_time=EventTime(timestamp=1775582468000, event_id=3097)) 0.034483
 Node(name=Soureh_design2, earliest_time=EventTime(timestamp=1277832623000, event_id=2727), latest_time=EventTime(timestamp=1774348808000, event_id=1874)) 0.023456
Node(name=moore_lynz45577, earliest_time=EventTime(timestamp=1313798783000, event_id=2315), latest_time=EventTime(timestamp=1773556779000, event_id=2332)) 0.021065
        Node(name=txemasg, earliest_time=EventTime(timestamp=1313798783000, event_id=2277), latest_time=EventTime(timestamp=1774348808000, event_id=2406)) 0.016806
    Node(name=Mr_Bhagat08, earliest_time=EventTime(timestamp=1313798783000, event_id=3116), latest_time=EventTime(timestamp=1774348808000, event_id=2920)) 0.016609
   Node(name=Person453112, earliest_time=EventTime(timestamp=1313798783000, event_id=3113), latest_time=EventTime(timestamp=1774348808000, event_id=2775)) 0.016580
          Node(name=zaibx, earliest_time=EventTime(timestamp=1313798783000, event_id=1980), latest_time=EventTime(timestamp=1774348808000, event_id=2018)) 0.015811
      Node(name=JeSuis34C, earliest_time=EventTime(timestamp=1313798783000, event_id=2910), latest_time=EventTime(timestamp=1772827192000, event_id=2769)) 0.015298
 Node(name=GhaithAhmed117, earliest_time=EventTime(timestamp=1313798783000, event_id=2713), latest_time=EventTime(timestamp=1774348808000, event_id=2672)) 0.014266
       Node(name=TimChowd, earliest_time=EventTime(timestamp=1313798783000, event_id=2832), latest_time=EventTime(timestamp=1773556779000, event_id=2554)) 0.013810
  Node(name=silversinergy, earliest_time=EventTime(timestamp=1313798783000, event_id=2089), latest_time=EventTime(timestamp=1774348808000, event_id=2278)) 0.013649
Node(name=Soundararajansm, earliest_time=EventTime(timestamp=1313798783000, event_id=2995), latest_time=EventTime(timestamp=1773556779000, event_id=2903)) 0.013334
      Node(name=tchemtcem, earliest_time=EventTime(timestamp=1313798783000, event_id=2041), latest_time=EventTime(timestamp=1774348808000, event_id=1674)) 0.012551
    Node(name=RHJOfficial, earliest_time=EventTime(timestamp=1313798783000, event_id=2262), latest_time=EventTime(timestamp=1773556779000, event_id=3098)) 0.011839
Node(name=xenosstinkriti2, earliest_time=EventTime(timestamp=1277832623000, event_id=1854), latest_time=EventTime(timestamp=1774348808000, event_id=2031)) 0.010902
    Node(name=BenUzi19770, earliest_time=EventTime(timestamp=1313798783000, event_id=3118), latest_time=EventTime(timestamp=1767737705000, event_id=2541)) 0.010828
     Node(name=UthamakiKE, earliest_time=EventTime(timestamp=1313798783000, event_id=3117), latest_time=EventTime(timestamp=1767737705000, event_id=3192)) 0.010604
Node(name=FernandezManu81, earliest_time=EventTime(timestamp=1313798783000, event_id=2249), latest_time=EventTime(timestamp=1774348808000, event_id=1739)) 0.010390
    Node(name=mayasdreams, earliest_time=EventTime(timestamp=1313798783000, event_id=1820), latest_time=EventTime(timestamp=1774348808000, event_id=1661)) 0.009893
     Node(name=SangZhi260, earliest_time=EventTime(timestamp=1313798783000, event_id=3114), latest_time=EventTime(timestamp=1774348808000, event_id=2043)) 0.009769
    Node(name=preetijjain, earliest_time=EventTime(timestamp=1313798783000, event_id=2714), latest_time=EventTime(timestamp=1774348808000, event_id=2485)) 0.009762
 Node(name=fahimiqbalemon, earliest_time=EventTime(timestamp=1240767057000, event_id=1698), latest_time=EventTime(timestamp=1774348808000, event_id=1773)) 0.009744
     Node(name=ModigWoman, earliest_time=EventTime(timestamp=1486036557000, event_id=1226), latest_time=EventTime(timestamp=1486036557000, event_id=3144)) 0.009545
         Node(name=KeivanS5, earliest_time=EventTime(timestamp=1240767057000, event_id=86), latest_time=EventTime(timestamp=1774348808000, event_id=2149)) 0.009245
    Node(name=untung_armi, earliest_time=EventTime(timestamp=1313798783000, event_id=2911), latest_time=EventTime(timestamp=1774348808000, event_id=1963)) 0.009046
Node(name=Revolution93843, earliest_time=EventTime(timestamp=1313798783000, event_id=2833), latest_time=EventTime(timestamp=1774348808000, event_id=2722)) 0.008872
          Node(name=ouitrvl, earliest_time=EventTime(timestamp=1236156014000, event_id=22), latest_time=EventTime(timestamp=1774742573000, event_id=1760)) 0.008769
  Node(name=NocturnalDoom, earliest_time=EventTime(timestamp=1313798783000, event_id=1992), latest_time=EventTime(timestamp=1774348808000, event_id=2175)) 0.008687
    Node(name=Oldbag12345, earliest_time=EventTime(timestamp=1240767057000, event_id=1847), latest_time=EventTime(timestamp=1774742573000, event_id=3198)) 0.008406
Node(name=MudassarAKLodhi, earliest_time=EventTime(timestamp=1313798783000, event_id=3112), latest_time=EventTime(timestamp=1620126309000, event_id=3138)) 0.008390
       Node(name=qqggpp86, earliest_time=EventTime(timestamp=1236156014000, event_id=1733), latest_time=EventTime(timestamp=1774742573000, event_id=1679)) 0.008263
       Node(name=alihstem, earliest_time=EventTime(timestamp=1240767057000, event_id=2013), latest_time=EventTime(timestamp=1766593751000, event_id=2646)) 0.008242
       Node(name=xixiltik, earliest_time=EventTime(timestamp=1236156014000, event_id=2055), latest_time=EventTime(timestamp=1775374085000, event_id=2466)) 0.007425
Node(name=Anonymouso32196, earliest_time=EventTime(timestamp=1236156014000, event_id=2028), latest_time=EventTime(timestamp=1775374085000, event_id=3200)) 0.007416
     Node(name=Mima091203, earliest_time=EventTime(timestamp=1236156014000, event_id=1664), latest_time=EventTime(timestamp=1775374085000, event_id=1995)) 0.007415
  Node(name=Richard_Prins, earliest_time=EventTime(timestamp=1236156014000, event_id=1634), latest_time=EventTime(timestamp=1775374085000, event_id=2078)) 0.007244
 Node(name=Bas642654743206, earliest_time=EventTime(timestamp=1277832623000, event_id=242), latest_time=EventTime(timestamp=1774348808000, event_id=2776)) 0.007047
   Node(name=elinggalatif, earliest_time=EventTime(timestamp=1236156014000, event_id=2215), latest_time=EventTime(timestamp=1775374085000, event_id=2809)) 0.006906
 Node(name=mannaggiaDegll, earliest_time=EventTime(timestamp=1775582468000, event_id=1485), latest_time=EventTime(timestamp=1775582468000, event_id=3097)) 0.006583
       Node(name=DKLarge2, earliest_time=EventTime(timestamp=1236156014000, event_id=1713), latest_time=EventTime(timestamp=1775390472000, event_id=3205)) 0.006437
 Node(name=zapanterablack, earliest_time=EventTime(timestamp=1236156014000, event_id=1823), latest_time=EventTime(timestamp=1775374085000, event_id=2425)) 0.006431
   Node(name=EBRU24071923, earliest_time=EventTime(timestamp=1236156014000, event_id=1850), latest_time=EventTime(timestamp=1775390472000, event_id=1830)) 0.006075
  Node(name=vulgarboatman, earliest_time=EventTime(timestamp=1236156014000, event_id=1816), latest_time=EventTime(timestamp=1775390472000, event_id=1657)) 0.005872
        Node(name=qaizimi, earliest_time=EventTime(timestamp=1236156014000, event_id=1775), latest_time=EventTime(timestamp=1775390472000, event_id=1796)) 0.005775
Node(name=RIPGeorgeHabash, earliest_time=EventTime(timestamp=1236156014000, event_id=1675), latest_time=EventTime(timestamp=1775390472000, event_id=1626)) 0.005567
 Node(name=ElsyObradorova, earliest_time=EventTime(timestamp=1236156014000, event_id=2750), latest_time=EventTime(timestamp=1775374085000, event_id=2960)) 0.005460
 Node(name=ysinvacaciones, earliest_time=EventTime(timestamp=1236156014000, event_id=1818), latest_time=EventTime(timestamp=1775390472000, event_id=1744)) 0.005435
       Node(name=bobreone, earliest_time=EventTime(timestamp=1236156014000, event_id=2464), latest_time=EventTime(timestamp=1775390472000, event_id=2132)) 0.005182
 Node(name=MontahaTarabey, earliest_time=EventTime(timestamp=1236156014000, event_id=2037), latest_time=EventTime(timestamp=1775390472000, event_id=1813)) 0.004964
    Node(name=jethalaalhu, earliest_time=EventTime(timestamp=1236156014000, event_id=3069), latest_time=EventTime(timestamp=1775374085000, event_id=3200)) 0.004947
     Node(name=Just_Ayiex, earliest_time=EventTime(timestamp=1236156014000, event_id=2240), latest_time=EventTime(timestamp=1775390472000, event_id=2516)) 0.004861
    Node(name=BeingHasan0, earliest_time=EventTime(timestamp=1754336265000, event_id=1527), latest_time=EventTime(timestamp=1754336265000, event_id=3141)) 0.004603
  Node(name=bibishalom330, earliest_time=EventTime(timestamp=1236156014000, event_id=1957), latest_time=EventTime(timestamp=1775390472000, event_id=1996)) 0.004541
  Node(name=bornwanderer2, earliest_time=EventTime(timestamp=1236156014000, event_id=2585), latest_time=EventTime(timestamp=1775390472000, event_id=2154)) 0.004516
     Node(name=ezbiderman, earliest_time=EventTime(timestamp=1236156014000, event_id=1655), latest_time=EventTime(timestamp=1775390472000, event_id=1659)) 0.004395
    Node(name=ieaglewatch, earliest_time=EventTime(timestamp=1236156014000, event_id=1888), latest_time=EventTime(timestamp=1775390472000, event_id=1868)) 0.004328
     Node(name=Hessamedia, earliest_time=EventTime(timestamp=1236156014000, event_id=1686), latest_time=EventTime(timestamp=1775390472000, event_id=1683)) 0.004301
        Node(name=fonzooe, earliest_time=EventTime(timestamp=1236156014000, event_id=2373), latest_time=EventTime(timestamp=1775390472000, event_id=2588)) 0.004299
  Node(name=JoannaTeglund, earliest_time=EventTime(timestamp=1236156014000, event_id=1882), latest_time=EventTime(timestamp=1775390472000, event_id=1643)) 0.004147
         Node(name=GM7077, earliest_time=EventTime(timestamp=1236156014000, event_id=2511), latest_time=EventTime(timestamp=1775390472000, event_id=2029)) 0.004045
    Node(name=anniefofani, earliest_time=EventTime(timestamp=1236156014000, event_id=1754), latest_time=EventTime(timestamp=1775390472000, event_id=1658)) 0.004000
     Node(name=d_normyle0, earliest_time=EventTime(timestamp=1236156014000, event_id=2509), latest_time=EventTime(timestamp=1775390472000, event_id=2108)) 0.003994
  Node(name=fightBackAnon, earliest_time=EventTime(timestamp=1236156014000, event_id=2322), latest_time=EventTime(timestamp=1775390472000, event_id=1960)) 0.003969
    Node(name=YoCambio20D, earliest_time=EventTime(timestamp=1236156014000, event_id=2510), latest_time=EventTime(timestamp=1775390472000, event_id=2378)) 0.003966
      Node(name=relewinde, earliest_time=EventTime(timestamp=1275204222000, event_id=1435), latest_time=EventTime(timestamp=1313798783000, event_id=3115)) 0.003872
        Node(name=risoflo, earliest_time=EventTime(timestamp=1743672831000, event_id=1508), latest_time=EventTime(timestamp=1772827192000, event_id=3103)) 0.003870
Node(name=EnriqueGarcaSo8, earliest_time=EventTime(timestamp=1236156014000, event_id=2957), latest_time=EventTime(timestamp=1775390472000, event_id=3205)) 0.003790
    Node(name=Ashborn_110, earliest_time=EventTime(timestamp=1236156014000, event_id=3199), latest_time=EventTime(timestamp=1775390472000, event_id=2976)) 0.003778
        Node(name=209asif, earliest_time=EventTime(timestamp=1236156014000, event_id=2392), latest_time=EventTime(timestamp=1775390472000, event_id=2327)) 0.003703
   Node(name=Abra_Company, earliest_time=EventTime(timestamp=1236156014000, event_id=2349), latest_time=EventTime(timestamp=1775390472000, event_id=2221)) 0.003703
Node(name=ExplosiveMediaa, earliest_time=EventTime(timestamp=1236156014000, event_id=1934), latest_time=EventTime(timestamp=1775390472000, event_id=1834)) 0.003653
    Node(name=Gokturk0034, earliest_time=EventTime(timestamp=1316016453000, event_id=2938), latest_time=EventTime(timestamp=1744925236000, event_id=3027)) 0.003653
Node(name=malik_musa14350, earliest_time=EventTime(timestamp=1675176080000, event_id=3147), latest_time=EventTime(timestamp=1675176080000, event_id=3147)) 0.003653
      Node(name=Iamdotun4, earliest_time=EventTime(timestamp=1313798783000, event_id=3111), latest_time=EventTime(timestamp=1313798783000, event_id=3111)) 0.003653

In [26]:
density = rp.algorithms.directed_graph_density(g)
print(f"Directed Graph Density: {density:.4f}")

Directed Graph Density: 0.2684

In [28]:
# Edge density of df_final
unique_nodes = pd.concat([df_final['target1'], df_final['target2']]).nunique()
unique_edges = df_final[['target1', 'target2']].drop_duplicates().shape[0]

edges_per_node = unique_edges / unique_nodes
# Directed graph density: edges / (n * (n - 1))
directed_density = unique_edges / (unique_nodes * (unique_nodes - 1))

print(f"Unique nodes:       {unique_nodes}")
print(f"Unique edges:       {unique_edges}")
print(f"Edges per node:     {edges_per_node:.4f}")
print(f"Directed density:   {directed_density:.6f}")

Unique nodes:       78
Unique edges:       1612
Edges per node:     20.6667
Directed density:   0.268398

In [29]:
clustering_coefficient = rp.algorithms.global_clustering_coefficient(g)
print(f"The graph's clustering coefficient is {clustering_coefficient}")

The graph's clustering coefficient is 0.7873097968668016

In [30]:
clustering = algorithms.louvain(g)

In [31]:
# Inspect structure first
sample_node, sample_val = next(iter(clustering.items()))
print(f"Cluster value structure: {sample_val}")

# Extract the actual cluster ID from the dict
unique_clusters = {next(iter(cluster.values())) for node, cluster in clustering.items()}
print(f"\nNumber of unique clusters: {len(unique_clusters)}")

Cluster value structure: {'community_id': 1}

Number of unique clusters: 2

In [32]:
labels = {0: 'Team_1', 1: 'Team_2', 2: 'Team_3'}
for node, cluster in clustering.items():
    cluster_id = next(iter(cluster.values()))          # fix 1: extract ID from dict
    g.node(node).set_node_type(labels[cluster_id])

print("Assigned node types based on clusters:")
for label in labels.values():
    nodes_in_cluster = [n.name for n in g.nodes if n.node_type == label]  # fix 2: g not G
    print(f"  {label}: {len(nodes_in_cluster)} nodes")

# Start a GraphQL server to explore in the UI
work_dir = tempfile.mkdtemp()
server = GraphServer(work_dir).start()                 # fix 3: GraphServer not graphql.GraphServer
client = server.get_client()
client.send_graph("cluster-graph", g, overwrite=True)
print(f"\nServer running at http://localhost:1736")
print(f"Open the Raphtory UI to explore the clustered graph")

Assigned node types based on clusters:
  Team_1: 44 nodes
  Team_2: 34 nodes
  Team_3: 0 nodes
  2026-04-10T13:28:45.245930Z  INFO raphtory_graphql::server: UI listening on 0.0.0.0:1736, live at: http://localhost:1736
    at raphtory-graphql/src/server.rs:217


Server running at http://localhost:1736
Open the Raphtory UI to explore the clustered graph

In [33]:
from collections import defaultdict

# Group nodes by their cluster ID
communities = defaultdict(list)
for node, cluster in clustering.items():
    cluster_id = next(iter(cluster.values()))  # or cluster["community"] etc.
    communities[cluster_id].append(node)

# Print each community and its members
for cluster_id, members in sorted(communities.items()):
    print(f"\nCluster {cluster_id} ({len(members)} nodes):")
    for m in members:
        print(f"  {m}")

Cluster 0 (44 nodes):
  Node(name=JeSuis34C, earliest_time=EventTime(timestamp=1313798783000, event_id=2910), latest_time=EventTime(timestamp=1772827192000, event_id=2769), node_type=Team_1)
  Node(name=Soureh_design2, earliest_time=EventTime(timestamp=1277832623000, event_id=2727), latest_time=EventTime(timestamp=1774348808000, event_id=1874), node_type=Team_1)
  Node(name=ouitrvl, earliest_time=EventTime(timestamp=1236156014000, event_id=22), latest_time=EventTime(timestamp=1774742573000, event_id=1760), node_type=Team_1)
  Node(name=DKLarge2, earliest_time=EventTime(timestamp=1236156014000, event_id=1713), latest_time=EventTime(timestamp=1775390472000, event_id=3205), node_type=Team_1)
  Node(name=TheBirmingham6, earliest_time=EventTime(timestamp=1313798783000, event_id=15), latest_time=EventTime(timestamp=1773556779000, event_id=1783), node_type=Team_1)
  Node(name=Mima091203, earliest_time=EventTime(timestamp=1236156014000, event_id=1664), latest_time=EventTime(timestamp=1775374085000, event_id=1995), node_type=Team_1)
  Node(name=mayasdreams, earliest_time=EventTime(timestamp=1313798783000, event_id=1820), latest_time=EventTime(timestamp=1774348808000, event_id=1661), node_type=Team_1)
  Node(name=farahadams, earliest_time=EventTime(timestamp=1313798783000, event_id=1735), latest_time=EventTime(timestamp=1775582468000, event_id=3097), node_type=Team_1)
  Node(name=RGemmell75, earliest_time=EventTime(timestamp=1772827192000, event_id=147), latest_time=EventTime(timestamp=1773556779000, event_id=1998), node_type=Team_1)
  Node(name=Oldbag12345, earliest_time=EventTime(timestamp=1240767057000, event_id=1847), latest_time=EventTime(timestamp=1774742573000, event_id=3198), node_type=Team_1)
  Node(name=DenyThemEssence, earliest_time=EventTime(timestamp=1516484875000, event_id=85), latest_time=EventTime(timestamp=1516484875000, event_id=3096), node_type=Team_1)
  Node(name=qqggpp86, earliest_time=EventTime(timestamp=1236156014000, event_id=1733), latest_time=EventTime(timestamp=1774742573000, event_id=1679), node_type=Team_1)
  Node(name=anniefofani, earliest_time=EventTime(timestamp=1236156014000, event_id=1754), latest_time=EventTime(timestamp=1775390472000, event_id=1658), node_type=Team_1)
  Node(name=JoannaTeglund, earliest_time=EventTime(timestamp=1236156014000, event_id=1882), latest_time=EventTime(timestamp=1775390472000, event_id=1643), node_type=Team_1)
  Node(name=tchemtcem, earliest_time=EventTime(timestamp=1313798783000, event_id=2041), latest_time=EventTime(timestamp=1774348808000, event_id=1674), node_type=Team_1)
  Node(name=moore_lynz45577, earliest_time=EventTime(timestamp=1313798783000, event_id=2315), latest_time=EventTime(timestamp=1773556779000, event_id=2332), node_type=Team_1)
  Node(name=FernandezManu81, earliest_time=EventTime(timestamp=1313798783000, event_id=2249), latest_time=EventTime(timestamp=1774348808000, event_id=1739), node_type=Team_1)
  Node(name=WOTCHA999, earliest_time=EventTime(timestamp=1516484875000, event_id=2767), latest_time=EventTime(timestamp=1773556779000, event_id=3102), node_type=Team_1)
  Node(name=RHJOfficial, earliest_time=EventTime(timestamp=1313798783000, event_id=2262), latest_time=EventTime(timestamp=1773556779000, event_id=3098), node_type=Team_1)
  Node(name=ModigWoman, earliest_time=EventTime(timestamp=1486036557000, event_id=1226), latest_time=EventTime(timestamp=1486036557000, event_id=3144), node_type=Team_1)
  Node(name=xenosstinkriti2, earliest_time=EventTime(timestamp=1277832623000, event_id=1854), latest_time=EventTime(timestamp=1774348808000, event_id=2031), node_type=Team_1)
  Node(name=Soundararajansm, earliest_time=EventTime(timestamp=1313798783000, event_id=2995), latest_time=EventTime(timestamp=1773556779000, event_id=2903), node_type=Team_1)
  Node(name=Person453112, earliest_time=EventTime(timestamp=1313798783000, event_id=3113), latest_time=EventTime(timestamp=1774348808000, event_id=2775), node_type=Team_1)
  Node(name=Revolution93843, earliest_time=EventTime(timestamp=1313798783000, event_id=2833), latest_time=EventTime(timestamp=1774348808000, event_id=2722), node_type=Team_1)
  Node(name=txemasg, earliest_time=EventTime(timestamp=1313798783000, event_id=2277), latest_time=EventTime(timestamp=1774348808000, event_id=2406), node_type=Team_1)
  Node(name=untung_armi, earliest_time=EventTime(timestamp=1313798783000, event_id=2911), latest_time=EventTime(timestamp=1774348808000, event_id=1963), node_type=Team_1)
  Node(name=Bas642654743206, earliest_time=EventTime(timestamp=1277832623000, event_id=242), latest_time=EventTime(timestamp=1774348808000, event_id=2776), node_type=Team_1)
  Node(name=NocturnalDoom, earliest_time=EventTime(timestamp=1313798783000, event_id=1992), latest_time=EventTime(timestamp=1774348808000, event_id=2175), node_type=Team_1)
  Node(name=Hessamedia, earliest_time=EventTime(timestamp=1236156014000, event_id=1686), latest_time=EventTime(timestamp=1775390472000, event_id=1683), node_type=Team_1)
  Node(name=TimChowd, earliest_time=EventTime(timestamp=1313798783000, event_id=2832), latest_time=EventTime(timestamp=1773556779000, event_id=2554), node_type=Team_1)
  Node(name=SangZhi260, earliest_time=EventTime(timestamp=1313798783000, event_id=3114), latest_time=EventTime(timestamp=1774348808000, event_id=2043), node_type=Team_1)
  Node(name=Ashborn_110, earliest_time=EventTime(timestamp=1236156014000, event_id=3199), latest_time=EventTime(timestamp=1775390472000, event_id=2976), node_type=Team_1)
  Node(name=MudassarAKLodhi, earliest_time=EventTime(timestamp=1313798783000, event_id=3112), latest_time=EventTime(timestamp=1620126309000, event_id=3138), node_type=Team_1)
  Node(name=GM7077, earliest_time=EventTime(timestamp=1236156014000, event_id=2511), latest_time=EventTime(timestamp=1775390472000, event_id=2029), node_type=Team_1)
  Node(name=fightBackAnon, earliest_time=EventTime(timestamp=1236156014000, event_id=2322), latest_time=EventTime(timestamp=1775390472000, event_id=1960), node_type=Team_1)
  Node(name=relewinde, earliest_time=EventTime(timestamp=1275204222000, event_id=1435), latest_time=EventTime(timestamp=1313798783000, event_id=3115), node_type=Team_1)
  Node(name=BeingHasan0, earliest_time=EventTime(timestamp=1754336265000, event_id=1527), latest_time=EventTime(timestamp=1754336265000, event_id=3141), node_type=Team_1)
  Node(name=mannaggiaDegll, earliest_time=EventTime(timestamp=1775582468000, event_id=1485), latest_time=EventTime(timestamp=1775582468000, event_id=3097), node_type=Team_1)
  Node(name=risoflo, earliest_time=EventTime(timestamp=1743672831000, event_id=1508), latest_time=EventTime(timestamp=1772827192000, event_id=3103), node_type=Team_1)
  Node(name=Abra_Company, earliest_time=EventTime(timestamp=1236156014000, event_id=2349), latest_time=EventTime(timestamp=1775390472000, event_id=2221), node_type=Team_1)
  Node(name=ExplosiveMediaa, earliest_time=EventTime(timestamp=1236156014000, event_id=1934), latest_time=EventTime(timestamp=1775390472000, event_id=1834), node_type=Team_1)
  Node(name=Gokturk0034, earliest_time=EventTime(timestamp=1316016453000, event_id=2938), latest_time=EventTime(timestamp=1744925236000, event_id=3027), node_type=Team_1)
  Node(name=malik_musa14350, earliest_time=EventTime(timestamp=1675176080000, event_id=3147), latest_time=EventTime(timestamp=1675176080000, event_id=3147), node_type=Team_1)
  Node(name=Iamdotun4, earliest_time=EventTime(timestamp=1313798783000, event_id=3111), latest_time=EventTime(timestamp=1313798783000, event_id=3111), node_type=Team_1)

Cluster 1 (34 nodes):
  Node(name=silversinergy, earliest_time=EventTime(timestamp=1313798783000, event_id=2089), latest_time=EventTime(timestamp=1774348808000, event_id=2278), node_type=Team_2)
  Node(name=qaizimi, earliest_time=EventTime(timestamp=1236156014000, event_id=1775), latest_time=EventTime(timestamp=1775390472000, event_id=1796), node_type=Team_2)
  Node(name=UthamakiKE, earliest_time=EventTime(timestamp=1313798783000, event_id=3117), latest_time=EventTime(timestamp=1767737705000, event_id=3192), node_type=Team_2)
  Node(name=BenUzi19770, earliest_time=EventTime(timestamp=1313798783000, event_id=3118), latest_time=EventTime(timestamp=1767737705000, event_id=2541), node_type=Team_2)
  Node(name=Richard_Prins, earliest_time=EventTime(timestamp=1236156014000, event_id=1634), latest_time=EventTime(timestamp=1775374085000, event_id=2078), node_type=Team_2)
  Node(name=ezbiderman, earliest_time=EventTime(timestamp=1236156014000, event_id=1655), latest_time=EventTime(timestamp=1775390472000, event_id=1659), node_type=Team_2)
  Node(name=RIPGeorgeHabash, earliest_time=EventTime(timestamp=1236156014000, event_id=1675), latest_time=EventTime(timestamp=1775390472000, event_id=1626), node_type=Team_2)
  Node(name=KeivanS5, earliest_time=EventTime(timestamp=1240767057000, event_id=86), latest_time=EventTime(timestamp=1774348808000, event_id=2149), node_type=Team_2)
  Node(name=fahimiqbalemon, earliest_time=EventTime(timestamp=1240767057000, event_id=1698), latest_time=EventTime(timestamp=1774348808000, event_id=1773), node_type=Team_2)
  Node(name=ysinvacaciones, earliest_time=EventTime(timestamp=1236156014000, event_id=1818), latest_time=EventTime(timestamp=1775390472000, event_id=1744), node_type=Team_2)
  Node(name=bobreone, earliest_time=EventTime(timestamp=1236156014000, event_id=2464), latest_time=EventTime(timestamp=1775390472000, event_id=2132), node_type=Team_2)
  Node(name=EBRU24071923, earliest_time=EventTime(timestamp=1236156014000, event_id=1850), latest_time=EventTime(timestamp=1775390472000, event_id=1830), node_type=Team_2)
  Node(name=fonzooe, earliest_time=EventTime(timestamp=1236156014000, event_id=2373), latest_time=EventTime(timestamp=1775390472000, event_id=2588), node_type=Team_2)
  Node(name=ieaglewatch, earliest_time=EventTime(timestamp=1236156014000, event_id=1888), latest_time=EventTime(timestamp=1775390472000, event_id=1868), node_type=Team_2)
  Node(name=zapanterablack, earliest_time=EventTime(timestamp=1236156014000, event_id=1823), latest_time=EventTime(timestamp=1775374085000, event_id=2425), node_type=Team_2)
  Node(name=zaibx, earliest_time=EventTime(timestamp=1313798783000, event_id=1980), latest_time=EventTime(timestamp=1774348808000, event_id=2018), node_type=Team_2)
  Node(name=vulgarboatman, earliest_time=EventTime(timestamp=1236156014000, event_id=1816), latest_time=EventTime(timestamp=1775390472000, event_id=1657), node_type=Team_2)
  Node(name=Anonymouso32196, earliest_time=EventTime(timestamp=1236156014000, event_id=2028), latest_time=EventTime(timestamp=1775374085000, event_id=3200), node_type=Team_2)
  Node(name=xixiltik, earliest_time=EventTime(timestamp=1236156014000, event_id=2055), latest_time=EventTime(timestamp=1775374085000, event_id=2466), node_type=Team_2)
  Node(name=elinggalatif, earliest_time=EventTime(timestamp=1236156014000, event_id=2215), latest_time=EventTime(timestamp=1775374085000, event_id=2809), node_type=Team_2)
  Node(name=Just_Ayiex, earliest_time=EventTime(timestamp=1236156014000, event_id=2240), latest_time=EventTime(timestamp=1775390472000, event_id=2516), node_type=Team_2)
  Node(name=MontahaTarabey, earliest_time=EventTime(timestamp=1236156014000, event_id=2037), latest_time=EventTime(timestamp=1775390472000, event_id=1813), node_type=Team_2)
  Node(name=YoCambio20D, earliest_time=EventTime(timestamp=1236156014000, event_id=2510), latest_time=EventTime(timestamp=1775390472000, event_id=2378), node_type=Team_2)
  Node(name=alihstem, earliest_time=EventTime(timestamp=1240767057000, event_id=2013), latest_time=EventTime(timestamp=1766593751000, event_id=2646), node_type=Team_2)
  Node(name=Mr_Bhagat08, earliest_time=EventTime(timestamp=1313798783000, event_id=3116), latest_time=EventTime(timestamp=1774348808000, event_id=2920), node_type=Team_2)
  Node(name=GhaithAhmed117, earliest_time=EventTime(timestamp=1313798783000, event_id=2713), latest_time=EventTime(timestamp=1774348808000, event_id=2672), node_type=Team_2)
  Node(name=preetijjain, earliest_time=EventTime(timestamp=1313798783000, event_id=2714), latest_time=EventTime(timestamp=1774348808000, event_id=2485), node_type=Team_2)
  Node(name=ElsyObradorova, earliest_time=EventTime(timestamp=1236156014000, event_id=2750), latest_time=EventTime(timestamp=1775374085000, event_id=2960), node_type=Team_2)
  Node(name=jethalaalhu, earliest_time=EventTime(timestamp=1236156014000, event_id=3069), latest_time=EventTime(timestamp=1775374085000, event_id=3200), node_type=Team_2)
  Node(name=bibishalom330, earliest_time=EventTime(timestamp=1236156014000, event_id=1957), latest_time=EventTime(timestamp=1775390472000, event_id=1996), node_type=Team_2)
  Node(name=d_normyle0, earliest_time=EventTime(timestamp=1236156014000, event_id=2509), latest_time=EventTime(timestamp=1775390472000, event_id=2108), node_type=Team_2)
  Node(name=bornwanderer2, earliest_time=EventTime(timestamp=1236156014000, event_id=2585), latest_time=EventTime(timestamp=1775390472000, event_id=2154), node_type=Team_2)
  Node(name=209asif, earliest_time=EventTime(timestamp=1236156014000, event_id=2392), latest_time=EventTime(timestamp=1775390472000, event_id=2327), node_type=Team_2)
  Node(name=EnriqueGarcaSo8, earliest_time=EventTime(timestamp=1236156014000, event_id=2957), latest_time=EventTime(timestamp=1775390472000, event_id=3205), node_type=Team_2)

In [ ]:
import sys
print(sys.executable)

/usr/local/bin/python3.12

In [ ]:
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "matplotlib"])

Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (2.4.1)
Requirement already satisfied: packaging>=20.0 in /Users/pj/Library/Python/3.12/lib/python/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

CompletedProcess(args=['/usr/local/bin/python3.12', '-m', 'pip', 'install', 'matplotlib'], returncode=0)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

plt.figure(figsize=(22, 18), dpi=150)

pos = nx.spring_layout(z, k=3, seed=42)

weights = np.array([z[u][v]['shared_followers'] for u, v in z.edges()])
normalized = (weights - weights.min()) / (weights.max() - weights.min())

nx.draw_networkx_nodes(z, pos, node_size=800, node_color="black", alpha=0.9)
nx.draw_networkx_labels(z, pos, font_size=8, font_color="white")
nx.draw_networkx_edges(
    z, pos,
    edge_color=normalized,
    edge_cmap=plt.cm.YlOrRd,
    width=2,
    alpha=0.8,
    arrows=True,
    arrowsize=15,
    connectionstyle="arc3,rad=0.1"
)

sm = plt.cm.ScalarMappable(cmap=plt.cm.YlOrRd, norm=plt.Normalize(weights.min(), weights.max()))
plt.colorbar(sm, ax=plt.gca(), label="Shared Followers")
plt.title("Twitter Follower Overlap Network", fontsize=16)
plt.axis("off")
plt.tight_layout()
plt.show()

NameError: name 'nx' is not defined